### ISSUE TITLE
Help: Bad array subscript

### ISSUE THREAD

**Issue by perara-chen** [bobbyiliev/introduction-to-bash-scripting#126]
### Please fill out this template

Error accessing last element from an array

### Additional context

I'm having problem when accessing the last item from an array. I followed exactly the same as written in the book.  Can someone explain me if I did something wrong? Thanks.

My script:
```
#!/bin/bash

my_array=("value 1" "value 2" "value 3" "value 4")

# Access item 1
echo ${my_array[1]}

# Access the last item
echo ${my_array[-1]}

# Access all the items
echo ${my_array[@]}

# Output total number of elements in the array
echo ${#my_array[@]}
```

Shell output:
```
value 2
script1.sh: line 9: my_array: bad array subscript

value 1 value 2 value 3 value 4
4
```

**Comment by bobbyiliev** [comment]
Hi there,

What version of bash are you using?

```
bash --version
```

Note that unsetting with negative index were only [added in bash 4.3](http://tiswww.case.edu/php/chet/bash/NEWS).

**Comment by blackcrack** [comment]
+hmm, if "value" ever the same why do you use not ever only the numbers ?
and if you use the "echo ${#my_array[@]}" then will echo the "value 1" from Array my_array..

how do you become "value 1"~ or, what want you directly working ? the whole "runtime" ?
```
blabla(){ 
?what want you do 
} 
```

so, Bashversion + my question :smiley: 

best

**Comment by perara-chen** [comment]
Thank you @bobbyiliev. Your pointer solved the problem. I forgot that I was using Apple's age-old bash. I ran the script on my Linux VM with bash 5.1.8 and everything worked well and the problem is solved. Thank you.

Apple's bash
```
GNU bash, version 3.2.57(1)-release (arm64-apple-darwin22)
Copyright (C) 2007 Free Software Foundation, Inc.
```

Script
```
#!/bin/bash

my_array=("value 1" "value 2" "value 3" "value 4")

# Access item 1
echo ${my_array[1]}

# Access the last item
echo ${my_array[-1]}

# Access all the items
echo ${my_array[@]}

# Output total number of elements in the array
echo ${#my_array[@]}
```

Output
```
value 2
value 4
value 1 value 2 value 3 value 4
4
```
