### ISSUE TITLE
Feature: When clicking the download button it should directly download the ebook.

### ISSUE THREAD

**Issue by Rohal004** [bobbyiliev/introduction-to-bash-scripting#134]
When Clicking the download button, it redirects to github where the book is uploaded. Some users might be not fimiliar with github so for user flexibility make it like who so ever clicks the download button it directly gets the book without getting confused.

**Comment by Gowrish7** [comment]
Hey Rohan , I can help you with that

**Comment by Rohal004** [comment]
Its's still open.

**Comment by Gowrish7** [comment]
Can you share any images of the issue so that i could understand it more clearly

**Comment by bobbyiliev** [comment]
@Gowrish7 it was a matter of just updating the links, I've done this already in #135

**Comment by Gowrish7** [comment]
> @Gowrish7 it was a matter of just updating the links, I've done this already in #135

Okay
