### ISSUE TITLE
Feature: Position of the Navigation Bar

### ISSUE THREAD

**Issue by Jils31** [bobbyiliev/introduction-to-bash-scripting#160]
### This feature should be added

The problem is the access of the navigation bar, as the other websites has this feature of accessing it anywhere from the page thus the user interaction on the page increases

### Solution

To fix this issue the position of the navigation bar should be fixed which make the website more interactive for the user

https://github.com/user-attachments/assets/5eb8c2f3-a582-4e6f-b596-a54ac13bab34

**Comment by Dhirajkushwaha3** [comment]
i can fix this just assign it to me.

**Comment by Neelesh19634** [comment]
please assign this issue to me

**Comment by bobbyiliev** [comment]
Thank you for the suggestion, but it is not really an issue as it is. I will close the issue for the moment.
