### ISSUE TITLE
Need Header Problem to be fixed 

### ISSUE THREAD

**Issue by Erayushsingh** [bobbyiliev/introduction-to-bash-scripting#163]
![image](https://github.com/user-attachments/assets/1a7246e1-efa8-4c29-81fb-df379744e7c2)

I fixes the header section of this webpage i.e. made it sticked on the webpage on scrolling 
Please assign this fixation or issue to me .
Please assign the Label of hactoberfest hacktoberfest-accepted 
So that I contribute to my first Open Source Contribution .
Please see my PR and merge it

**Comment by krrakshit** [comment]
can you please assign me this issue ??

**Comment by bobbyiliev** [comment]
Thank you for the suggestion, but it is not really an issue as it is. I will close the issue for the moment.
