### ISSUE TITLE
Enhancing Interactive Training and Blog Content

### ISSUE THREAD

**Issue by Erayushsingh** [bobbyiliev/introduction-to-bash-scripting#164]
Hi  @bobbyiliev ,

![image](https://github.com/user-attachments/assets/ddf62901-f9d2-4062-b72d-b8128b0b13e8)
![image](https://github.com/user-attachments/assets/34aa5bec-3248-4480-b80d-b6859a1b7eb4)

I hope this message finds you well. I would like to request permission to take on the issue regarding adding content to the Interactive Training web page and the About section of our blog. I believe I can contribute effectively to this project and help enhance user engagement.

Please let me know if I can proceed with this assignment. I appreciate your consideration and label this issue with hacktoberfest hacktoberfest-accepted.

Best regards,
Ayush

**Comment by bobbyiliev** [comment]
Hey! Thank you for brining this up! The training page has been removed as Katacoda has been deprecated unfortunately:

<img width="1305" alt="image" src="https://github.com/user-attachments/assets/0164dad4-be65-4290-9d67-2954cd08a6bb">

Feel free to contribute to the book itself!
