### ISSUE TITLE
Feature: Making the buttons active like write bash 

### ISSUE THREAD

**Issue by Bhumika-00** [bobbyiliev/introduction-to-bash-scripting#165]
### Is your feature request related to a problem? Please describe.
I will make the buttons active in order to get the direct understanding of the topic.
### Describe the solution you'd like
I will add a link which will take the user on the other page as well as add CSS when the div/button will be active.
@liigo @edent @ezerw @shmick @marcelozarate

**Comment by marcelozarate** [comment]
Hi! I'm not sure if this belongs here, this repo belongs to the book, not the site.
