### ISSUE TITLE
Feature: slice of $@ in Arguments

### ISSUE THREAD

**Issue by mgvalverde** [bobbyiliev/introduction-to-bash-scripting#17]
Hi, 

First thanks for book,  I have been using it recently and I find it pretty handy.

The second, I think it would be useful to add some example explaining how to access to a slice of $@,  in the section "Arguments" . 
Something like the solution found [here](https://stackoverflow.com/questions/9057387/process-all-arguments-except-the-first-one-in-a-bash-script).

Thanks!

**Comment by bobbyiliev** [comment]
Hi there 👋,

Thank you for pointing this out! Very good point! I will make sure to add this to the chapter!

Regards,
Bobby

**Comment by vipul-2003** [comment]
Hi, I am vipul kumar 

I would like to contribute to this issue , would you explain
Me what should i have to do in more detail  ....??
@bobbyiliev
