### ISSUE TITLE
Feature: 

### ISSUE THREAD

**Issue by IcHiGo-KuRoSaKiI** [bobbyiliev/introduction-to-bash-scripting#28]
### Is your feature request related to a problem? Please describe.

You have not added the links to the chapters in the README.MD file
### Describe the solution you'd like
I can add all the links to the content in your README.MD

### Additional context
please assign me this issue for hacktoberfest 2021

**Comment by bobbyiliev** [comment]
Just assigned you, looking forward to your contribution!
