### ISSUE TITLE
Feature: heredoc and herestrings

### ISSUE THREAD

**Issue by ek234** [bobbyiliev/introduction-to-bash-scripting#40]
Would you like to include heredoc and herestrings in the redirection section?

I believe that this would be very helpful for bash scripters.

**Comment by ek234** [comment]
Ohh I just saw this. Will get right into it.

**Comment by bobbyiliev** [comment]
Thank you for the PR! Just merged it: https://github.com/bobbyiliev/introduction-to-bash-scripting/pull/47
