### ISSUE TITLE
"Substring in Bash :: Slicing" - in wrong place?

### ISSUE THREAD

**Issue by PaulWalkerUK** [bobbyiliev/introduction-to-bash-scripting#49]
Page 27 and 28 feel a bit out of place. The section is called "Substring in Bash :: Slicing", but all the examples talk about arrays which aren't introduced until page 29. It might make more sense if the examples were changed to be based on normal strings rather than arrays, or swap the sections?

**Comment by bobbyiliev** [comment]
This is a good point! Thank you for bringing this up. I'll take a look at it now
