### ISSUE TITLE
Feature: Make epub to better experience

### ISSUE THREAD

**Issue by mruncleleon** [bobbyiliev/introduction-to-bash-scripting#52]
### Is your feature request related to a problem? Please describe.

Hi, firstly thanks for this book. It's awesome work but in PDF is dificult to read in cellphone  while go to work.

### Describe the solution you'd like

I finded a tool called pandoc that make epub file from md files. More info here:
https://pandoc.org/epub.html

### Additional context

I think pandoc will help to build books by language when people start to translate them.

**Comment by bobbyiliev** [comment]
We no have an ePub variation! Thanks to @edent 🚀 

I've created a new issue for the GitHub action to automate this too:
https://github.com/bobbyiliev/introduction-to-bash-scripting/issues/77
