### ISSUE TITLE
[Request] Open Discussions Forum

### ISSUE THREAD

**Issue by blackcrack** [bobbyiliev/introduction-to-bash-scripting#58]
could we have here a Discussions Forum, to ask different questions around bash and scripts ?
For have the users a Platform here where can ask short for loop, arrays or others in bash.. how ever.. 
my wanted help do i now set as issue ;)

best

**Comment by bobbyiliev** [comment]
That is a great idea! Thank you for the suggestion!

This should now be all setup:

https://github.com/bobbyiliev/introduction-to-bash-scripting/discussions/75
