### ISSUE TITLE
Bug: 008 bash Array.md 

### ISSUE THREAD

**Issue by vipul-2003** [bobbyiliev/introduction-to-bash-scripting#66]
## Describe the bug

I was reading the book to revise my concepts , while revising i have noted that 008-bash array file has bug in .md file 
```shell
my_array=("1""2""3""4""5")
echo ${#my_array[@]} --this will print only the first value not  the total no. of elements
```

__Explainig Syntax error with screenshot__
![image](https://user-images.githubusercontent.com/72446442/193518630-39d58db3-48f0-4f2d-9c86-12dc1ba956b7.png)

## Correct Way of Writing 👍 
```shell
echo ${#my_array}  --this will print the number of elements in my array 
```

## Attached Screenshot  (for sake of proof) 
![image](https://user-images.githubusercontent.com/72446442/193518168-00845d31-4db5-47cb-8cf1-759390d2f7e0.png)

please assign this to me , i will fix accordingly ...

Thanks you ❤️

**Comment by vipul-2003** [comment]
have a look @bobbyiliev 👀

**Comment by bobbyiliev** [comment]
Thank you! Just commented under the PR and will close this issue.
