### ISSUE TITLE
Feature: Create a GitHub action to automate the Pandoc epub generation after each merge to main

### ISSUE THREAD

**Issue by bobbyiliev** [bobbyiliev/introduction-to-bash-scripting#77]
### Is your feature request related to a problem? Please describe.

Similar to what we have with Ibis, create the same action but for Pandoc!

For more information on the Pandoc integration, check out this PR here:

https://github.com/bobbyiliev/introduction-to-bash-scripting/pull/60

**Comment by mph7** [comment]
Hello, I'm creating an action to use in the project, and I'm using the ibis one as a reference, when I get it working I will submit a pull request!
Can you please assign this issue to me?

**Comment by bobbyiliev** [comment]
Sounds good! I've just assigned you!

**Comment by bobbyiliev** [comment]
Close as completed!
