### ISSUE TITLE
Feature: Translating in diffrent languages

### ISSUE THREAD

**Issue by blackcrack** [bobbyiliev/introduction-to-bash-scripting#8]
### Is your feature request related to a problem? Please describe.

not any understand very easy englisch

### Describe the solution you'd like

for better understanding translating in different languages

### Additional context

- nothing

**Comment by bobbyiliev** [comment]
Hi there,

That is a good point! I personally only know English and Bulgarian, anyone who feels enthusiastic, please feel free to submit a PR with a transalation!

**Comment by JimmyOlano** [comment]
¡ Hi ! I am Castilian language native (AKA _Spanish_) and medium level English language but about Bulgarian language... nothing.

¿ How works translations, what is the mechanism ? (¿ PR meaning ? ).

¡Thanks in advance, have a nice day! 8-)

**Comment by bobbyiliev** [comment]
Hi there @JimmyOlano 👋,

I have restructured the repository to allow additional translations.

What you need to do is:

* Copy the `./ebook/en` folder to `./ebook/{LANG}` (change {LANG} with the language that you want to contribute, eg. `es`, `de`, `bg` and etc) 
* Then translate all files in the content folder
* Submit a PR
* I will then review and generate the PDF files so that you don't have to install ibis

Thanks!
Regards,
Bobby

**Comment by Ak8933** [comment]
hey @bobbyiliev should I try it ?

**Comment by bobbyiliev** [comment]
@Ak8933 sure give it a try! 🙌

**Comment by KarmaTashiCat** [comment]
[KarmaTashiCat:feature/translations_es](https://github.com/bobbyiliev/introduction-to-bash-scripting/pull/123)

**Comment by KarmaTashiCat** [comment]
#

> 

# #123

**Comment by KarmaTashiCat** [comment]
#123

**Comment by BlackeyeB** [comment]
Hi, may do I the ebook chapter's 15 translation to spanish?

**Comment by blackcrack** [comment]
hmmm.. i have a idea.. for translating.. there was befor a couple weeks a new translateer with Video as Handy app where greate a video with sound and Face-aiming in the specific language and with really less errors, it was in the german  morning Magacine of the german SAT TV, why not use something as automatic translating and correcting only if need, how far some AI translater be is remarkable, why should not we have something in bash as automatic translater to "con", for have all in in the user language.. maby seted up in .bashrc autoaitrans=de_DE .. .. so just a idea ..
best
Blacky
