### ISSUE TITLE
Feature: i just want to add favicon for this website and that will will your logo and will look attractive after adding this.

### ISSUE THREAD

**Issue by shubham21155102** [bobbyiliev/introduction-to-bash-scripting#83]

**Comment by bobbyiliev** [comment]
Ok sounds good!

**Comment by shrn01** [comment]
Looks like the website does have a favicon no?

https://ebook.bobby.sh/

**Comment by blackcrack** [comment]
```
<link rel="icon" href="/favicon.png" type="image/png">
```
Saving this image as favicon.png
![favicon](https://user-images.githubusercontent.com/7925717/194752033-263623c6-58bb-4d2a-9760-e9a9af121a1b.png)

Technical details : [https://en.wikipedia.org/wiki/Favicon](https://en.wikipedia.org/wiki/Favicon)

best

**Comment by shrn01** [comment]
Isn't this repo the source code of that particular site?

**Comment by bobbyiliev** [comment]
> Isn't this repo the source code of that particular site?

Yep this is correct!

https://github.com/bobbyiliev/introduction-to-bash-scripting/blob/main/index.html
