### ISSUE TITLE
Feature: Include version number

### ISSUE THREAD

**Issue by rsgranne** [bobbyiliev/introduction-to-bash-scripting#9]
### Is your feature request related to a problem? Please describe.

I downloaded your book some time in the past. However, I don’t know when. I have no idea which release of your book I downloaded. If I want to download a new version, I can’t compare it to the version I currently have because there is nowhere in the book that has a version number.

### Describe the solution you'd like

Easy — include a version number in your text. Also, a copyright or copyleft notice, or a clear statement of license, would be nice as well. 

Thanks for a great book!

**Comment by bobbyiliev** [comment]
Thanks for pointing that out! That sounds like a very good point! I will try to work on that the next few days!

**Comment by bobbyiliev** [comment]
Thanks for pointing that out! I have added a note at the beginning of the book showing the date when the PDF was generated and the version!
